# Nombre: Arturo Lazcano
## RUT: 20.470.051-6

# CC3001 Primavera 2020 Tarea 3
## Multiplicación de Polinomios
## Profesores
Sección 1 Benjamin Bustos • Sección 2 Jérémy Barbay • Sección 3 Patricio Poblete / Nelson Baloian

El objetivo de esta tarea es implementar y comparar los dos algoritmos de multiplicación de polinomios que aparecen en el apunte: el algoritmo por fuerza bruta y el que utiliza la técnica de diseño "Dividir para Reinar", que de acuerdo al análisis realizado toma tiempo $\Theta(n^{1.59})$. Para esta tarea, los coeficientes a considerar son de tipo entero.

## Algoritmo cuadrático

La función ``multpol`` implementa el algoritmo de multiplicación de polinomios por fuerza bruta, que toma tiempo $\Theta(n^2)$.

In [39]:
import numpy as np

def multpol(a, b):
    '''
    multpol: array array -> array
    Recibe dos arreglos, a y b, que contienen los coeficientes de los polinomios
    (valores enteros), y devuelve un arreglo con los coeficientes resultantes de
    multiplicar ambos polinomios. Ambos arreglos deben tener el mismo largo
    Ejemplo: 
    Sea pol1 = [-1, 2, -3, 4] el arreglo que representa al polinomio -1 + 2x -3x**2 + 4x**3
    Sea pol2 = [0, 0, 0, 2] el arreglo que representa al polinomio 2x**3
    multpol(pol1, pol2) devuelve el arreglo [0, 0, 0, -2, 4, -6, 8], que corresponde al
    polinomio -2x**3 + 4x**4 - 6x**5 + 8x**6
    '''
    n = len(a)
    assert len(b) == n
    c = np.zeros(2 * n - 1, dtype = int)
    for i in range(0, n):
        for j in range(0, n):
            c[i + j] += a[i] * b[j]
    return c

# Test
pol1 = np.array([-1, 2, -3, 4], dtype = int)
pol2 = np.array([0, 0, 0, 2], dtype = int)
resultado = np.array([0, 0, 0, -2, 4, -6, 8], dtype = int)
assert np.array_equal(multpol(pol1, pol2), resultado)

In [40]:
multpol(np.array([2, 3, -6, 1, 2, 0, 4, 1], dtype = int), np.array([1, -1, 3, 1, 4, -2, 0, 2], dtype = int))


array([  2,   1,  -3,  18,  -6,   3, -19,  19,  23,  -9,  19,   0,  -2,
         8,   2])

## Algoritmo basado en Dividir para Reinar

A continuación, implemente el algoritmo de multiplicación de polinomios que utiliza tres multiplicaciones recursivas, que toma tiempo $\Theta(n^{1.59})$. Para implementar este algoritmo, puede suponer que el tamaño de los arreglos es siempre una potencia de 2.

In [41]:
import numpy as np

def multpol2(a, b):
    '''
    multpol2: array array -> array
    Recibe dos arreglos, a y b, que contienen los coeficientes de los polinomios
    (valores enteros), y devuelve un arreglo con los coeficientes resultantes de
    multiplicar ambos polinomios. Utiliza el algoritmo recursivo basado en
    Dividir para Reinar visto en catedra, que realiza tres llamados recursivos.
    Ambos arreglos deben tener el mismo largo
    Ejemplo: 
    Sea pol1 = [2, 3, -6, 1, 2, 0, 4, 1] el arreglo que representa al
    polinomio 2 + 3x - 6x**2 + x**3 + 2x**4 + 4x**6 + x**7
    Sea pol2 = [1, -1, 3, 1, 4, -2, 0, 2] el arreglo que representa al
    polinomio 1 - x + 3x**2 + x**3 + 4x**4 - 2x**5 + 2x**7
    multpol(pol1, pol2) devuelve el arreglo
    [2, 1, -3, 18, -6, 3, -19, 19, 23, -9, 19, 0, -2, 8, 2], que corresponde al
    polinomio 2 + x - 3x**2 + 18x**3 - 6x**4 + 3x**5 - 19x**6 + 19x**7 + 23x**8 - 
    9x**9 + 19x**10 - 2x**12 + 8x*13 + 2x**14 
    '''
    # Implemente su algoritmo aqui
    n=len(a)
    assert n==len(b)
    A1=a[:n//2]
    A2=a[n//2:]
    B1=b[:n//2]
    B2=b[n//2:]
    if n==1:
        return a*b
    elif n==2:
        E=a[0]*b[0]
        F=a[1]*b[1]
        D=(a[0]+a[1])*(b[0]+b[1])
        C=np.append(np.append(E,(D-E-F)),F)
        return C
    else:
        E=multpol2(A1,B1)
        F=multpol2(A2,B2)
        D=multpol2((A1+A2),(B1+B2))
        aux0=np.array([0])
        C=np.append(np.append(E,aux0),F)
        k=(len(E)+1)//2
        C[k:(len(C)-k)]+=(D-E-F)
        return C
    
# Tests
pol1 = np.array([-1, 2, -3, 4], dtype = int)
pol2 = np.array([0, 0, 0, 2], dtype = int)
resultado = np.array([0, 0, 0, -2, 4, -6, 8], dtype = int)
assert np.array_equal(multpol2(pol1, pol2), resultado)
pol1 = np.array([2,3,-6,1,2,0,4,1], dtype = int)
pol2 = np.array([1,-1,3,1,4,-2,0,2], dtype = int)
resultado = np.array([2, 1, -3, 18, -6, 3, -19, 19, 23, -9, 19, 0, -2, 8, 2], dtype = int)
assert np.array_equal(multpol2(pol1, pol2), resultado)

Ahora, muestre ejemplos de uso de su función ``multpol2``, mostrando el resultado para al menos cuatro ejemplos distintos de multiplicaciones de polinomios, con grados de polinomios distintos para cada ejemplo.

In [42]:
# Implemente sus ejemplos de uso aquí
# Ejemplo1
pol1 = np.array([-24], dtype = int)
pol2 = np.array([3], dtype = int)
print(multpol2(pol1,pol2))
# Ejemplo2
pol1 = np.array([-8,6], dtype = int)
pol2 = np.array([3,-6], dtype = int)
print(multpol2(pol1,pol2))
# Ejemplo3
pol1 = np.array([1,6,-4,8,5,0,-3,-2], dtype = int)
pol2 = np.array([0,0,0,0,0,0,4,-1], dtype = int)
print(multpol2(pol1,pol2))
# Ejemplo4
pol1 = np.array([1,2,3,4,0,0,0,0,4,3,2,1,0,0,0,0], dtype = int)
pol2 = np.array([2,-2,2,-2,0,0,1,1,-1,-1,2,4,0,0,0,10], dtype = int)
print(multpol2(pol1,pol2))

[-72]
[-24  66 -36]
[  0   0   0   0   0   0   4  23 -22  36  12  -5 -12  -5   2]
[ 2  2  4  4 -6  2 -7  3 12  2  7 -3  6 18 18 17 21 26 44 19 15 10  4 40
 30 20 10  0  0  0  0]


# Comparación de ambos algoritmos para $n$ grande

La función ``%timeit`` de Python permite medir el tiempo tomado para la ejecución de una función. Por ejemplo, el siguiente código genera dos polinomios representados por arreglos aleatorios de tamaño $n$, y luego calcula cuánto demora en ejecutarse la función ``multpol`` para multiplicar ambos polinomios.

In [43]:
n = 16
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
%timeit multpol(a,b)

297 µs ± 47.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Implemente ahora un experimento para descubrir a partir de qué valor de $n$ la función ``multpol2`` es más eficiente que la función ``multpol``. Utilice valores de $n$ que sean potencias de 2 para realizar este experimento. Pruebe con al menos diez valores distintos de $n$.

In [44]:
# Implemente su experimento aqui
#n=2
n = 2
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol (n=2):")
%timeit multpol(a,b)
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol2 (n=2):")
%timeit multpol2(a,b)
#n=4
n = 4
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol (n=4):")
%timeit multpol(a,b)
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol2 (n=4):")
%timeit multpol2(a,b)
#n=16
n = 16
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol (n=16):")
%timeit multpol(a,b)
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol2 (n=16):")
%timeit multpol2(a,b)
#n=32
n = 32
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol (n=32):")
%timeit multpol(a,b)
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol2 (n=32):")
%timeit multpol2(a,b)
#n=64
n = 64
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol (n=64):")
%timeit multpol(a,b)
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol2 (n=64):")
%timeit multpol2(a,b)
#n=128
n = 128
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol (n=128):")
%timeit multpol(a,b)
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol2 (n=128):")
%timeit multpol2(a,b)
#n=256
n = 256
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol (n=256):")
%timeit multpol(a,b)
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol2 (n=256):")
%timeit multpol2(a,b)
#n=512
n = 512
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol (n=512):")
%timeit multpol(a,b)
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol2 (n=512):")
%timeit multpol2(a,b)
#n=1024
n = 1024
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol (n=1024):")
%timeit multpol(a,b)
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol2 (n=1024):")
%timeit multpol2(a,b)
#n=1024
n = 1024
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol (n=2048):")
%timeit multpol(a,b)
a = np.random.randint(-10, 10, n)
b = np.random.randint(-10, 10, n)
print("Tiempo ejecución multpol2 (n=2048):")
%timeit multpol2(a,b)

Tiempo ejecución multpol (n=2):
8.68 µs ± 551 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
Tiempo ejecución multpol2 (n=2):
31 µs ± 4.38 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Tiempo ejecución multpol (n=4):
23.3 µs ± 3.57 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Tiempo ejecución multpol2 (n=4):
108 µs ± 6.67 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Tiempo ejecución multpol (n=16):
310 µs ± 24.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
Tiempo ejecución multpol2 (n=16):
1.08 ms ± 47.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
Tiempo ejecución multpol (n=32):
1.05 ms ± 32.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
Tiempo ejecución multpol2 (n=32):
3.11 ms ± 175 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Tiempo ejecución multpol (n=64):
4.12 ms ± 152 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Tiempo ejecución multpol2 (n=64):
9.2 ms ± 457 µs 

[Explique los resultados de su experimento en esta celda]  
### Conclusión
Se probó con 10 números distintos potencias de 2 (2, 4, 16, 32, 64, 128, 256, 512, 1024 y 2048) y se puede observar que desde el número 256 ya existe una diferencia de tiempo entre los dos algoritmos, a favor del método de ``multpol2``. Con este experimento se puede concluir que, a pesar que ``multpol2`` hace efectivamente menos multiplicaciones, el hecho de crear arrays, concatenarlos y sumarlos hace un trabajo considerable pero para números relativamente altos este algoritmo es bastante más eficiente, pues ``multpol`` crece exponencialmente.